# Generated by Django 4.2.3 on 2023-08-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0002_symbol_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='icon',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
