# Generated by Django 4.2.3 on 2023-08-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0003_symbol_icon_alter_symbol_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='is_active',
            new_name='is_popular',
        ),
    ]
